package ru.rt.eu.arm.common.sign.test;

import lombok.Getter;

@Getter
enum TestKeyData {

    GOST_2001(
            "TUlHUkFnRUFNQkVHQmlxRkF3SUNFd1lIS29VREFnSWpBUVI1TUhjQ0FRRUVJSGVNTGxPMjdwMEJQYVhOZWVxSU51c05XSkk5OHlRMnRIVGtNSS9COTRBUm9Ba0dCeXFGQXdJQ0l3R2hSUU5EQUFSQTdCWmN4dEc5ZmNBRkowc1ByRmgzMUcweVpuZFRVZWd2TlplWkNPam95dGlrY3hpSWNSS0xrRjVzTzMydnFHL3pyMW9PbHNBVUUvL2EvdFdBQlN2K1F3PT0=",
            "MIICAzCCAbACCQCRwSrCqVBfCjAKBgYqhQMCAgMFADCBhzELMAkGA1UEBhMCUlUxDzANBgNVBAgMBk1vc2NvdzEPMA0GA1UEBwwGTW9zY293MQwwCgYDVQQKDANOQ0kxDjAMBgNVBAsMBUVHSVNaMRUwEwYDVQQDDAxhcm0ucnQtZXUucnUxITAfBgkqhkiG9w0BCQEWEmVnaXN6LWFkbUBydC1ldS5ydTAeFw0xODA0MDYwNzQ2MDhaFw0yODA0MDMwNzQ2MDhaMIGHMQswCQYDVQQGEwJSVTEPMA0GA1UECAwGTW9zY293MQ8wDQYDVQQHDAZNb3Njb3cxDDAKBgNVBAoMA05DSTEOMAwGA1UECwwFRUdJU1oxFTATBgNVBAMMDGFybS5ydC1ldS5ydTEhMB8GCSqGSIb3DQEJARYSZWdpc3otYWRtQHJ0LWV1LnJ1MGMwHAYGKoUDAgITMBIGByqFAwICIwEGByqFAwICHgEDQwAEQMa3B6lusXw8/5FaydYwfHoqtlKy3eNFUj2FBVhZqOYcmNMbaAgtLyYiLSkZcJcqdOgoMur4qDRIdLZwjxhV/rwwCgYGKoUDAgIDBQADQQB11MpwTus8zGCyAWauJsKFW+83AVEf/hyAertg2BByzwvlK0ju6QCT0xiZQ+OyEE3k4YIhGzXcsv22l9l31FHI"),
    GOST_2012_256("", ""), // todo add values
    GOST_2012_512("", ""); // todo add values

    private String key;
    private String certificate;

    TestKeyData(String key, String certificate) {
        this.key = key;
        this.certificate = certificate;
    }
}
